name: astor_mobile
description: "TKM 8"
publish_to: 'none'
version: 8.0.1+9

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  get_storage: ^2.1.1
  flutter_bootstrap: ^2.0.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^1.1.1
  dio: ^5.0.0
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.0
  path_provider: ^2.1.0
  font_awesome_flutter: ^10.7.0
  device_info_plus: ^10.1.0
  workmanager: ^0.9.0+3
  file_picker: any
  flutter_colorpicker: any
  image_picker: any
  intl: any
  reflectable: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  reflectable: any
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/config.env

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/tkm.logo.only.png
