name: astormobile
description: "Astor mobile"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  get_storage: ^2.1.1
  flutter_bootstrap: ^2.0.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

